-- USER SQL
CREATE USER "C##proyecto_twi" IDENTIFIED BY "proyecto"  
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "C##proyecto_twi" QUOTA UNLIMITED ON "SYSTEM";
ALTER USER "C##proyecto_twi" QUOTA UNLIMITED ON "USERS";

-- ROLES

-- SYSTEM PRIVILEGES
GRANT CREATE JOB TO "C##proyecto_twi" ;
GRANT CREATE TRIGGER TO "C##proyecto_twi" ;
GRANT CREATE MATERIALIZED VIEW TO "C##proyecto_twi" ;
GRANT CREATE VIEW TO "C##proyecto_twi" ;
GRANT CREATE SESSION TO "C##proyecto_twi" ;
GRANT CREATE TABLE TO "C##proyecto_twi" ;
GRANT CREATE TYPE TO C##proyecto_twi" ;
GRANT CREATE PUBLIC DATABASE LINK TO "C##proyecto_twi" ;
GRANT CREATE SEQUENCE TO "C##proyecto_twi" ;
GRANT CREATE PROCEDURE TO "C##proyecto_twi" ;

